### ISSUE TITLE
Gif static

### ISSUE THREAD

**Issue by noahfraiture** [BourgeoisBear/rasterm#4]
Hello, 
I use kitty and the gif doesn't move like it should with icat. Is it normal?

**Comment by BourgeoisBear** [comment]
I just wrap their API, which is frame-based.  To do animation, you'll have to send it frame-by-frame like icat does:

https://github.com/kovidgoyal/kitty/blob/b9051d82888017cc89363b0e7aa1fbd38751f8b0/kittens/icat/native.go#L141

I believe the only interface for doing a direct upload of animated gifs is the iTerm/WezTerm one--the one that kitty doesn't support:

https://pkg.go.dev/github.com/BourgeoisBear/rasterm#ItermCopyFileInline

**Comment by noahfraiture** [comment]
Ok I see ty.
I would like this feature, I can make a PR if you want. Do you have indication where to start ? Sadly you seem to only support png for now and not other image format tho, I would have to do that too

**Comment by BourgeoisBear** [comment]
rasterm is intended as a thin wrapper over popular inline image protocols.  It only supports direct PNG and "raw" in kitty because those are the only formats supported by kitty's protocol:

https://sw.kovidgoyal.net/kitty/graphics-protocol/

iTerm protocol supports a broader range of encodings, but only works in iTerm, Wezterm, & mintty, and is not specific about what it handles, since iTerm seems to defer most of the actual handling to macOS:

https://iterm2.com/documentation-images.html

Things outside of the inline protocols should go in a new project.

**Comment by noahfraiture** [comment]
I understand what you're saying, however gif animation is literally in your todo file. Is it supposed to be there ?

**Comment by BourgeoisBear** [comment]
https://github.com/BourgeoisBear/rasterm/commit/9daf9e15f423a780da83d7c3de85d0ff13606c2b

Between `KittyImgOpts`, and the ability to specify extra options in  `ToHeader()`, rasterm should already have everything you need to upload the frames.  I respect Kovid, but I am also not inclined to pave-over the potholes in Kitty's overwrought protocol.  There's a saying we have in this business: "*If you touch it, it's yours.*"

https://sw.kovidgoyal.net/kitty/graphics-protocol/#animation

**Comment by noahfraiture** [comment]
Ok I see, thank you for your answer. I started a [fork](https://github.com/noahfraiture/rasterm) if you want, I can make a PR once I'm done.

**Comment by BourgeoisBear** [comment]
If you are going to rename public functions, please rename the project as well.  I cannot accept any PR from this, because in https://github.com/noahfraiture/rasterm/commit/748558feecb30e3f73daafa2e9f825c817ab50f7 you broke the API.
